version: '3'
services:
    backend:
        build:
            context: '.'
            dockerfile: './docker/backend.dockerfile'
        volumes:
            - './database/data.sqlite:/app/database/data.sqlite:ro'
            - './server/config.json:/app/server/config.json:ro'
            - './server/logs:/app/server/logs'
            - './tmp:/app/tmp'

    frontend:
        build: 
            context: '.'
            dockerfile: './docker/frontend.dockerfile'
            args:
                APP_PATH: /methylscape
        environment:
            API_BASE_URL: http://backend:10000
            APP_PATH: /methylscape
        ports: 
            - '8100:80'

    database:
        image: postgres
        environment:
            POSTGRES_USER: methylscape
            POSTGRES_PASSWORD: methylscape
            POSTGRES_DB: methylscape
        ports:
          - '5432:5432'
