version: "3"
services:
  database:
    image: postgres
    environment:
      POSTGRES_USER: methylscape
      POSTGRES_PASSWORD: methylscape
      POSTGRES_DB: methylscape
    ports:
      - "5432:5432"
