version: '3'
services:
    backend:
        build:
            context: '.'
            dockerfile: './docker/backend.dockerfile'
        volumes:
            - './database:/database'
            - './server/config.json:/server/config.json'

    frontend:
        build: 
            context: '.'
            dockerfile: './docker/frontend.dockerfile'
            args:
                APP_PATH: /methylscape
        environment:
            API_HOST: http://backend
            API_PORT: 10000
            APP_PATH: /methylscape
        ports: 
            - '8100:80'

