AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Specification template describing your function.
Resources:
  updateMethylscapeTable:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: s3://methylscape-lambda/97f797d007b35facd8e009f4fb45cc7e
      Description: ''
      MemorySize: 128
      Timeout: 3
      Policies:
      - AmazonDynamoDBFullAccess
      - AmazonS3ReadOnlyAccess
      Events:
        S3FileListener:
          Type: S3
          Properties:
            Bucket:
              Ref: MethylscapeBucket
            Events:
            - s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                - Name: prefix
                  Value: ClassifierReports/
  MethylscapeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: methylscape
